name: Production Build
on: [push]
jobs:
  production-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_WORKSPACE}"
      - run: ./mvnw clean package -Pproduction -X -Dhilla.mavenExecutable="${GITHUB_WORKSPACE}/mvnw"
